version: v1

labels:
  - label: area/workflow
    sync: true
    matcher:
      files: ".github/**"

  - label: area/module-actor
    sync: true
    matcher:
      files: "packages/module-actor/**"

  - label: area/module-api
    sync: true
    matcher:
      files: "packages/module-api/**"

  - label: area/module-database
    sync: true
    matcher:
      files: "packages/module-database/**"
