version: v1

labels:
  - label: area/workflow
    sync: true
    matcher:
      files: ".github/**"

  - label: area/module-api
    sync: true
    matcher:
      files: "packages/module.api/**"

  - label: area/module-database
    sync: true
    matcher:
      files: "packages/module.database/**"

  - label: area/module-defid
    sync: true
    matcher:
      files: "packages/module.defid/**"

  - label: area/module-health
    sync: true
    matcher:
      files: "packages/module.health/**"

  - label: area/module-indexer
    sync: true
    matcher:
      files: "packages/module.indexer/**"

  - label: area/module-model
    sync: true
    matcher:
      files: "packages/module.model/**"
