version: "2"

checks:
  similar-code:
    enabled: true
    config:
      threshold: 75

exclude_patterns:
  - "dist/"
  - "**/node_modules/"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/*.spec/"
  - "**/*.d.ts"
